version: '3'

networks:
  emaily:
    driver: bridge

services:
  james:
    depends_on:
      - elasticsearch
      - cassandra
      - tika
      - rabbitmq
      - s3
    image: linagora/tmail-backend:distributed-0.4.0
    container_name: james
    hostname: james.local
    ports:
      - "80:80"     # JMAP
      - "25:25"     # SMTP without authentication
      - "110:110"   # POP3
      - "143:143"   # IMAP
      - "465:465"   # SMTP with authentication and socketTLS enabled
      - "587:587"   # SMTP with authentication and startTLS enabled
      - "993:993"   # IMAP with socketTLS enabled
      - "8000:8000" # Web Admin interface (unsecured: expose at your own risks)
    networks:
      - emaily
    # environment:
    #   - JAVA_TOOL_OPTIONS=-Xmx500m -Xms500m -javaagent:/root/glowroot/glowroot.jar

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    volumes:
      - tmail_elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    networks:
      - emaily

  cassandra:
    image: cassandra:3.11.10
    volumes:
      - tmail_cassandra_data:/var/lib/cassandra
    ports:
      - "9042:9042"
    networks:
      - emaily

  tika:
    image: apache/tika:1.24
    networks:
      - emaily

  rabbitmq:
    image: rabbitmq:3.8.17-management
    volumes:
      - tmail_rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - emaily

  s3:
    image: zenko/cloudserver:8.2.6
    container_name: s3.docker.test
    volumes:
      - tmail_cloudserver_data:/usr/src/app/localData
      - tmail_cloudserver_metadata:/usr/src/app/localMetadata
    environment:
      - SCALITY_ACCESS_KEY_ID=${SCALITY_ACCESS_KEY_ID}
      - SCALITY_SECRET_ACCESS_KEY=${SCALITY_SECRET_ACCESS_KEY}
      - S3DATAPATH=/usr/src/app/localData
      - S3METADATAPATH=/usr/src/app/localMetadata
      # - LOG_LEVEL=trace
      # - REMOTE_MANAGEMENT_DISABLE=1
    networks:
      - emaily

volumes:
  tmail_elasticsearch_data:
    driver_opts:
      type: none
      device: ${VOLUMES_ROOT}/elasticsearch/data
      o: bind
  tmail_cassandra_data:
    driver_opts:
      type: none
      device: ${VOLUMES_ROOT}/cassandra/data
      o: bind
  tmail_rabbitmq_data:
    driver_opts:
      type: none
      device: ${VOLUMES_ROOT}/rabbitmq/data
      o: bind
  tmail_cloudserver_data:
    driver_opts:
      type: none
      device: ${VOLUMES_ROOT}/cloudserver/data
      o: bind
  tmail_cloudserver_metadata:
    driver_opts:
      type: none
      device: ${VOLUMES_ROOT}/cloudserver/metadata
      o: bind
